//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLevel
    {
        public int Id { get; set; }
        public string Level { get; set; }
        public decimal RefundRate { get; set; }
        public int MemberCount { get; set; }
        public decimal MemberArchievement { get; set; }
        public decimal Archievement { get; set; }
    }
}
