//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.CashTransaction = new HashSet<CashTransaction>();
            this.PointTransaction = new HashSet<PointTransaction>();
            this.MyMembers = new HashSet<Member>();
            this.BaoDanTransaction = new HashSet<BaoDanTransaction>();
            this.ChongXiaoTransaction = new HashSet<ChongXiaoTransaction>();
            this.LockedCoin = new HashSet<LockedCoin>();
            this.BankInfo = new HashSet<BankInfo>();
            this.IPLog = new HashSet<IPLog>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string Password1 { get; set; }
        public string Password2 { get; set; }
        public string Password3 { get; set; }
        public decimal Cash1 { get; set; }
        public decimal Cash2 { get; set; }
        public decimal Point1 { get; set; }
        public decimal Point2 { get; set; }
        public decimal ChongXiao1 { get; set; }
        public decimal ChongXiao2 { get; set; }
        public decimal Coin1 { get; set; }
        public decimal Coin2 { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public string Level { get; set; }
        public decimal Achievement { get; set; }
        public string Status { get; set; }
        public string TiXianStatus { get; set; }
        public string TiBiStatus { get; set; }
        public Nullable<bool> IdSubmitted { get; set; }
        public Nullable<bool> IdApproved { get; set; }
        public string ApprovedBy { get; set; }
    
        public virtual ICollection<CashTransaction> CashTransaction { get; set; }
        public virtual ICollection<PointTransaction> PointTransaction { get; set; }
        public virtual Member Referral { get; set; }
        public virtual ICollection<Member> MyMembers { get; set; }
        public virtual ICollection<BaoDanTransaction> BaoDanTransaction { get; set; }
        public virtual ICollection<ChongXiaoTransaction> ChongXiaoTransaction { get; set; }
        public virtual ICollection<LockedCoin> LockedCoin { get; set; }
        public virtual ICollection<BankInfo> BankInfo { get; set; }
        public virtual ICollection<IPLog> IPLog { get; set; }
    }
}
