//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashTransactions
    {
        public CashTransactions()
        {
            this.PaymentMethods = new HashSet<PaymentMethods>();
        }
    
        public int Id { get; set; }
        public int MemberId { get; set; }
        public decimal Amount { get; set; }
        public System.TimeSpan DateTime { get; set; }
        public short Type { get; set; }
        public short Status { get; set; }
    
        public virtual ICollection<PaymentMethods> PaymentMethods { get; set; }
        public virtual Members Members { get; set; }
    }
}
