//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public Members()
        {
            this.CashTransactions = new HashSet<CashTransactions>();
            this.Members1 = new HashSet<Members>();
            this.PointTransactions = new HashSet<PointTransactions>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password1 { get; set; }
        public string Password2 { get; set; }
        public string Password3 { get; set; }
        public decimal Cash1 { get; set; }
        public decimal Cash2 { get; set; }
        public decimal Point1 { get; set; }
        public decimal Point2 { get; set; }
        public decimal ChongXiao1 { get; set; }
        public decimal ChongXiao2 { get; set; }
        public decimal Coin1 { get; set; }
        public decimal Coin2 { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public string Level { get; set; }
        public int Referral_Id { get; set; }
    
        public virtual ICollection<CashTransactions> CashTransactions { get; set; }
        public virtual ICollection<Members> Members1 { get; set; }
        public virtual Members Members2 { get; set; }
        public virtual ICollection<PointTransactions> PointTransactions { get; set; }
    }
}
