//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethods
    {
        public int Id { get; set; }
        public string Bank { get; set; }
        public string Account { get; set; }
        public string Description { get; set; }
        public int CashTransaction_Id { get; set; }
    
        public virtual CashTransactions CashTransactions { get; set; }
    }
}
