//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public int Id { get; set; }
        public string Bank { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Type { get; set; }
        public Nullable<int> Member_Id { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
