//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoDanTransactions
    {
        public BaoDanTransactions()
        {
            this.CashTransactions = new HashSet<CashTransactions>();
            this.ChongXiaoTransactions = new HashSet<ChongXiaoTransactions>();
            this.LockedCoins = new HashSet<LockedCoins>();
            this.PointTransactions = new HashSet<PointTransactions>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal Amount { get; set; }
        public decimal Price { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public int MemberId { get; set; }
        public decimal Fee { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<CashTransactions> CashTransactions { get; set; }
        public virtual ICollection<ChongXiaoTransactions> ChongXiaoTransactions { get; set; }
        public virtual ICollection<LockedCoins> LockedCoins { get; set; }
        public virtual ICollection<PointTransactions> PointTransactions { get; set; }
        public virtual Member Members { get; set; }
    }
}
