//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public Members()
        {
            this.BankInfo = new HashSet<BankInfo>();
            this.BaoDanTransactions = new HashSet<BaoDanTransactions>();
            this.CashTransactions = new HashSet<CashTransactions>();
            this.ChongXiaoTransactions = new HashSet<ChongXiaoTransactions>();
            this.IPLogs = new HashSet<IPLogs>();
            this.LockedCoins = new HashSet<LockedCoins>();
            this.Members1 = new HashSet<Members>();
            this.PointTransactions = new HashSet<PointTransactions>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string Password1 { get; set; }
        public string Password2 { get; set; }
        public decimal Cash1 { get; set; }
        public decimal Cash2 { get; set; }
        public decimal Point1 { get; set; }
        public decimal Point2 { get; set; }
        public decimal ChongXiao1 { get; set; }
        public decimal ChongXiao2 { get; set; }
        public decimal Coin1 { get; set; }
        public decimal Coin2 { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public decimal Achievement { get; set; }
        public string Mobile { get; set; }
        public string Status { get; set; }
        public string TiXianStatus { get; set; }
        public string TiBiStatus { get; set; }
        public Nullable<bool> IdSubmitted { get; set; }
        public Nullable<bool> IdApproved { get; set; }
        public string IdentityPath { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> Referral_Id { get; set; }
        public int MemberLevel_Id { get; set; }
    
        public virtual ICollection<BankInfo> BankInfo { get; set; }
        public virtual ICollection<BaoDanTransactions> BaoDanTransactions { get; set; }
        public virtual ICollection<CashTransactions> CashTransactions { get; set; }
        public virtual ICollection<ChongXiaoTransactions> ChongXiaoTransactions { get; set; }
        public virtual ICollection<IPLogs> IPLogs { get; set; }
        public virtual ICollection<LockedCoins> LockedCoins { get; set; }
        public virtual MemberLevel MemberLevel { get; set; }
        public virtual ICollection<Members> Members1 { get; set; }
        public virtual Members Members2 { get; set; }
        public virtual ICollection<PointTransactions> PointTransactions { get; set; }
    }
}
