//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLevel
    {
        public MemberLevel()
        {
            this.Members = new HashSet<Member>();
        }
    
        public int Id { get; set; }
        public string Level { get; set; }
        public decimal RefundRate { get; set; }
        public int MemberCount { get; set; }
        public decimal MemberAchievement { get; set; }
        public decimal Achievement { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
