//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomJobs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VapEntities : DbContext
    {
        public VapEntities()
            : base("name=VapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankInfo> BankInfo { get; set; }
        public virtual DbSet<BaoDanTransactions> BaoDanTransactions { get; set; }
        public virtual DbSet<CashTransactions> CashTransactions { get; set; }
        public virtual DbSet<ChongXiaoTransactions> ChongXiaoTransactions { get; set; }
        public virtual DbSet<CoinPrices> CoinPrices { get; set; }
        public virtual DbSet<IPLogs> IPLogs { get; set; }
        public virtual DbSet<LockedCoins> LockedCoins { get; set; }
        public virtual DbSet<MemberLevel> MemberLevel { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<PaymentMethods> PaymentMethods { get; set; }
        public virtual DbSet<PointTransactions> PointTransactions { get; set; }
        public virtual DbSet<SysStatistics> SysStatistics { get; set; }
        public virtual DbSet<SystemSettings> SystemSettings { get; set; }
    }
}
